### ISSUE TITLE
Mobile view for orderlist

### ISSUE THREAD

**Issue by jakobehn** [cloudystuff/orderweb#2]
```[tasklist]
### Tasks
- [ ] https://github.com/cloudystuff/orderweb/issues/33
- [ ] https://github.com/cloudystuff/orderweb/issues/34
- [ ] https://github.com/cloudystuff/orderweb/issues/35
- [ ] https://github.com/cloudystuff/orderweb/issues/36
```
